# Game settings and constants

# Player settings
PLAYER_JUMP_HEIGHT = 4
PLAYER_JUMP_DURATION = 0.6
PLAYER_DUCK_DURATION = 0.5
PLAYER_LANE_WIDTH = 4

# Game mechanics
INITIAL_GAME_SPEED = 15
GAME_SPEED_INCREASE_RATE = 0.1
LANE_POSITIONS = [-PLAYER_LANE_WIDTH, 0, PLAYER_LANE_WIDTH]

# Vision control thresholds
VISION_LANE_LEFT_THRESHOLD = 0.4
VISION_LANE_RIGHT_THRESHOLD = 0.6
VISION_DUCK_THRESHOLD = 0.1

# Camera settings
CAMERA_POSITION = (0, 8, -15)
CAMERA_ROTATION = (20, 0, 0)
